---
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    open-pull-requests-limit: 10
    schedule:
      interval: 'weekly'
      day: 'friday'

  - package-ecosystem: 'npm'
    directory: '/frontend/src/'
    open-pull-requests-limit: 10
    schedule:
      interval: 'weekly'
      day: 'friday'

  - package-ecosystem: 'docker'
    directory: '/frontend/'
    open-pull-requests-limit: 10
    schedule:
      interval: 'weekly'
      day: 'friday'
