version: '3.8'

services:
  # cli is an init container, after db is running
  # add migration: dc run --rm cli bash -c 'yarn supabase migration new name_in_snake_case'
  # reset db: dc run --rm cli bash -c 'yarn supabase db reset --db-url=$DATABASE_URL'
  # gen types: dc run --rm cli bash -c 'curl http://meta:8080/generators/typescript > types/database.types.ts'
  nuxt:
    platform: linux/amd64
    image: ghcr.io/jniclas/honesty:1.0.5
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 3000:3000
      - 24678:24678
    environment:
      HOST: 0.0.0.0
      DATABASE_URL: postgresql://supabase_admin:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      WEB_PUSH_PRIVATE_KEY: "AkniGohWNz9SqMSjEYfTXkpc7nX59rXPJnwry0tFM9Q"
      NUXT_PUBLIC_WEB_PUSH_PUBLIC_KEY: "BMxJ3PKxHF6I78nmXaHcPsZd4aXSiNJs75Qq3hP5ES4pbLm4QQZ_PODPP3emkF1xZewAxZ2Jtb6OsBrMU9uZn6U"
      WEB_PUSH_SUBJECT: "mailto:jniclasg@googlemail.com"
      API_EXTERNAL_URL: https://supabase-api.niiclas.de
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ewogICAgInJvbGUiOiAiYW5vbiIsCiAgICAiaXNzIjogInN1cGFiYXNlIiwKICAgICJpYXQiOiAxNjkxMTg2NDAwLAogICAgImV4cCI6IDE4NDkwMzkyMDAKfQ.Ztlvz0iioEr7cbhTWSaYDCaGpAUKqvzliQbgcyONJZM
      SUPABASE_SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ewogICAgInJvbGUiOiAic2VydmljZV9yb2xlIiwKICAgICJpc3MiOiAic3VwYWJhc2UiLAogICAgImlhdCI6IDE2OTExODY0MDAsCiAgICAiZXhwIjogMTg0OTAzOTIwMAp9.JZPjeZUgWjvcoxNjrIyr3cFeKRhJU-N1xrEey5Thj8Q
    volumes:
      - ./src:/home/app/src
      - ./volumes/db/migrations:/home/app/supabase/migrations
      - ./src/types:/home/app/types
    working_dir: /home/app/src
    # command: bash -c "yarn install && rm -rf /tmp/nitro && yarn dev"
    # command: bash -c "yarn supabase db push --db-url=$$DATABASE_URL && curl ${META_SERVICE_URL}generators/typescript > types/database.types.ts && yarn install && rm -rf /tmp/nitro && yarn dev"

