{{- if .Values.studio.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.studio.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  {{- if not .Values.studio.autoscaling.enabled }}
  replicas: {{ .Values.studio.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "supabase.studio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.studio.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "supabase.studio.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.studio.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "supabase.studio.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.studio.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "supabase.studio.name" $ }}
          securityContext:
            {{- toYaml .Values.studio.securityContext | nindent 12 }}
          image: "{{ .Values.studio.image.repository }}:{{ .Values.studio.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.studio.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.studio.environment }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ include "supabase.studio.fullname" $ }}
                  key: {{ $key }}
            {{- end }}
            - name: SUPABASE_URL
              value: https://{{ if ne .Release.Name "prod" }}{{ .Release.Name }}-{{ end }}{{ .Values.application.name }}-api.{{ .Values.domain.name }}
            - name: SUPABASE_REST_URL
              value: https://{{ if ne .Release.Name "prod" }}{{ .Release.Name }}-{{ end }}{{ .Values.application.name }}-api.{{ .Values.domain.name }}/rest/v1/
            - name: STUDIO_PG_META_URL
              value: http://{{ include "supabase.kong.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:8000/pg
            - name: SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.secret.fullname" . }}-jwt
                  key: anonKey
            - name: SUPABASE_SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.secret.fullname" . }}-jwt
                  key: serviceKey
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          {{- with .Values.studio.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.studio.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.studio.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.studio.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.studio.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.studio.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}