apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "supabase.db.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  imageName: ghcr.io/jniclas/supabase-cloudnativedb:15.1.0.118
  postgresql:
    pg_hba:
      - host all all all password
  resources: 
    limits:
      memory: 1Gi
      cpu: 1
      # 'hugepages-2Mi': 512Mi
    requests:
      memory: 1Gi
      cpu: 1
      # 'hugepages-2Mi': 512Mi
  storage:
    size: 2Gi
    storageClass: openebs-jiva-csi-default
  monitoring:
    enablePodMonitor: true
  superuserSecret:
    name: {{ .Values.db.secretName }}
  bootstrap:
    initdb:
      database: postrgres
      owner: app
      secret:
        name: {{ .Values.db.secretName }}
      dataChecksums: true
      encoding: 'UTF8'
      postInitApplicationSQLRefs:
        configMapRefs:
        - name: {{ include "supabase.db.fullname" . }}-init
          key: configmap.sql