apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: {{ include "supabase.db.fullname" . }}-rw
spec:
  cluster:
    name: {{ include "supabase.db.fullname" . }}

  instances: 3
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
      ignore_startup_parameters: extra_float_digits,search_path