apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.frontend.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ if ne .Release.Name "prod" }}{{ .Release.Name }}-{{ end }}{{ .Values.application.name }}.{{ .Values.domain.name }}"
    external-dns.alpha.kubernetes.io/access: private
    external-dns.alpha.kubernetes.io/ttl: "30"
    external-dns.alpha.kubernetes.io/endpoints-type: HostIP # NodeExternalIP
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "supabase.frontend.selectorLabels" . | nindent 4 }}
